### ISSUE TITLE
port Lister machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#10]
![lister](https://user-images.githubusercontent.com/27146/38279228-2a63e4d6-3754-11e8-800a-8183db099b94.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_lister.py

Lister is responsible for fetching a recent list of active Nameplates from the rendezvous/mailbox server. It is used by the Input machine each time the user hits TAB while typing in the nameplate portion of the wormhole code (or when a GUI application wants to populate a drop-down menu for code entry). It remembers that we currently want (or don't want) a listing, and it knows whether we're connected to the server or not. It sends a NAMEPLATES request at the right time (through the Rendezvous machine), and delivers any response to the Input machine.

**Comment by copyninja** [comment]
I'm working on this in my fork on `input-helper` branch.

**Comment by warner** [comment]
this is done
