### ISSUE TITLE
port Mailbox machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#11]
![mailbox](https://user-images.githubusercontent.com/27146/38279323-97c8c79e-3754-11e8-882d-d8c80fd8c8d3.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_mailbox.py

Mailbox manages the messages our client exchanges with our peer client. It's one of the more compex machines (along with Nameplate).

On the server, Nameplates are pointers to a Mailbox object. Nameplates are short strings, Mailboxes are long random strings. The Nameplate is released as quickly as possible (once both sides have opened their mailbox), to free up the namespace and let the nameplate be used by some other client.. The Mailbox stays open as long as both clients are running, and since they're long and random, there's no pressure to conserve them or free them up quickly.

We might acquire the Mailbox by going through a Nameplate, or we might open one directly (e.g. if we use a Wormhole Seed, or we're re-opening a previous connection somehow). But we want to release the Mailbox when we're done using it. And our connection to the server might go up and down while we're running.

Our Mailbox machine keeps track of mailbox allocation: it remembers whether we want the mailbox to be open or not, it remembers if we've sent an Open request that might not have been received yet, and the same for a Close. If we're told to open the Mailbox but we don't currently have a connection, then the next time the connection opens we'll send the Open message. Freeing/closing the mailbox is similar.

The Maibox machine also manages the messages we send out, and the ones we receive. It queues outbound messages until we have a connection to send them on, and doesn't remove them from the queue until the server echoes it back (indicating that it's been received by the server, which then takes responsibility for delivery to the peer).

Any inbound message tells us that our peer has opened the mailbox, which means they don't need the Nameplate anymore, so we tell our Nameplate machine that it can release the nameplate.

**Comment by vu3rdd** [comment]
grabbing this one.

**Comment by vu3rdd** [comment]
We have good parts of this in the repository now as part of #26.

**Comment by warner** [comment]
This one is done now
