### ISSUE TITLE
port Receive machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#14]
![receive](https://user-images.githubusercontent.com/27146/38280220-01666ad6-3759-11e8-9b40-a69b7a5e25f8.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_receive.py

The Receive machine is responsible for decrypting inbound messages, and keeping track of when our key becomes "verified" (meaning we've seen at least one validly-encrypted message using our PAKE-generated shared encryption key).

It receives the encryption key from Key, and messages from Order, and sends decrypted plaintexts to Boss. It also notifies Send when the key has been verified (which waits until that point to encrypt and send any queued outbound application messages), and tells Boss about mood changes ("happy" when the key is verified, and "scared" when we see a badly-encrypted message).

**Comment by vu3rdd** [comment]
#33 implements this machine.

**Comment by warner** [comment]
this is done now
