### ISSUE TITLE
port Send machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#16]
![send](https://user-images.githubusercontent.com/27146/38280950-f3007f78-375c-11e8-99da-2f1434f4a12a.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_send.py

Send is a simple machine that manages the transmission of encrypted application messages. It is told about the shared encryption key by Key (after it has been verified by receipt of the peer's Version message), and is given outbound plaintexts by Boss. It encrypts these and delivers the ciphertext to Mailbox for delivery. Any messages which arrive before the key has been computed are queued until afterwards: this allows applications to call `w.send_message()` without waiting for something like `w.get_verifier()` or `w.get_next_message()`.

**Comment by vu3rdd** [comment]
Going to look at this next.

**Comment by vu3rdd** [comment]
#33 has an initial implementation of the `send` and `receive` machines.

**Comment by copyninja** [comment]
#34 adds code to generate side but due to side affects of github changes made it into already open PR.

**Comment by warner** [comment]
this is done now
