### ISSUE TITLE
port Terminator machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#17]
![terminator](https://user-images.githubusercontent.com/27146/38281026-6ea0fb3a-375d-11e8-9848-ec14efda5400.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_terminator.py

The Terminator machine handles wormhole shutdown. We want to be polite and clean up after ourselves, so we try to release the Nameplate and Mailbox structures on the server. Terminator tracks which of these tasks have been finished and which have not. If `w.close()` has been called but we don't currently have a server connection, we wait until we've got one, send the Release and Close messages, wait for them to be acknowleged, then tell Rendezvous that we don't need the connection anymore, wait for it to be dropped, and finally notify Boss that we can shut down. Boss then delivers a Closed message to the API layer.

If Nameplate is told to release the nameplate for other reasons (i.e. we have the mailbox, and we see evidence that our peer has the mailbox, so we don't need it any more), and it successfully releases it, it tells Terminator so we don't need to wait for anything else during shutdown. The same happens with the mailbox. And if both have been released, we don't need a connection (and if the connection just happened to have been lost at the moment the application calls `w.close()`, then when Terminator tells Rendezvous to stop, it will send back Stopped immediately because it's already disconnected).

The state names refer to the set of resources that are still active: `n` for nameplate, `m` for mailbox, and `o` for an open (non-closed) Wormhole. The initial state is `Snmo`, meaning all are still active, and as we receive word that resources have been freed, we remove letters from the state name.

The Terminator machine, like all machines, is created at the same time as the rest of the Wormhole, and receives events as the rest of the machines do their business. So the most likely progression of states is from the initial `Snmo`, to `Smo` as the nameplate is released, then `Sm` as `w.close()` is called (upon which Boss tells Mailbox that we don't need one anymore, so it releases it), then `S_stopping` after the mailbox CLOSED is received (at which point Terminator tells Rendezvous to tear down the websocket connection, and not reestablish a new one), then `S_stopped` when the connection is finally lost. At this point it tells Boss that we're done.

This doesn't really have to be managed by a state machine: a simple vector of booleans might be sufficient.

**Comment by copyninja** [comment]
I'm implementing this in `terminator-machine` branch of my fork

**Comment by warner** [comment]
this is done and pretty thoroughly tested
