### ISSUE TITLE
port Allocator machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#5]
![allocator](https://user-images.githubusercontent.com/27146/38278372-9ab7e2ea-3750-11e8-8e50-edef29697e7a.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_allocator.py

The Allocator is responsible for creating a code, which consists of a Nameplate (the short integer at the start of a wormhole code, like the `4` in `4-purple-sausages`) and some random words. This is driven by Code, when the application uses the `w.allocate_code()` API. It must wait until we're connected, then send an `allocate` message to the mailbox/rendezvous server. If we lose the connection, a new message must be sent upon reconnection. When a response is received, the server-provided nameplate is combined with locally-generated random words, and the combined code is delivered to the Code machine, then we're done.

This will live in `core/src/allocator.rs`.

**Comment by copyninja** [comment]
I'm working on this in my fork branch `input-helper`

**Comment by warner** [comment]
I've looked at the Allocator code and I think it's complete, but we should add a couple of tests to close this ticket.

**Comment by warner** [comment]
6968987d07b54c6189738b90cf4569aa4f014657 added the tests, closing this now.
