### ISSUE TITLE
port Input machine

### ISSUE THREAD

**Issue by warner** [warner/magic-wormhole.rs#8]
![input](https://user-images.githubusercontent.com/27146/38278704-fc1c3c1a-3751-11e8-8644-33d402855ec6.png)

https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/_input.py

The Input machine handles the `w.input_code()` case, and helps with interactive (tab-completion) entry of the wormhole code. In the Python API, `w.input_code()` returns an "Input Helper" with its own API: for our sans-io approach, the API layer will own this helper object, and we need to add API events/actions to let the API layer's object communicate with the core's Input machine.

The Input machine communicates with the Lister object to obtain the list of active Nameplates (from the mailbox/rendezvous server), and delivers its results to the Code object (both the intermediate `got_nameplate` phase and the final `finished_input` event).

**Comment by copyninja** [comment]
I started working on but got a bit struck in between. I see many states in python code which might be missing in above state diagram. I understand some of those states are invoked by helper but I'm just wondering if we can merge helper into input machine itself?.

**Comment by warner** [comment]
This port looks good enough for now, so I'll close this.

I'm not entirely sure about the helper API, but the Input machine itself has the three functions the helper will need (`get_nameplate_completions`, `get_word_completions`, and one named `committed_nameplate` which maybe should go away). The main `WormholeCore` object has methods which pass through to these three.
